# Dockerfile.flin
FROM python:3.9
WORKDIR /app
COPY requirements.txt /app/
RUN pip install -r requirements.txt
COPY cont2.py /app/
COPY env_2.json /app/
CMD ["uvicorn", "cont2:app", "--host", "0.0.0.0", "--port", "8001"]
