# Dockerfile.fer
FROM python:3.9
WORKDIR /app
COPY requirements.txt /app/
RUN pip install -r requirements.txt
COPY cont1.py /app/
COPY env.json /app/
CMD ["uvicorn", "cont1:app", "--host", "0.0.0.0", "--port", "8000"]
